site_name: How to use Fetch API

theme:
  name: material
  palette:
    primary: 'green'
    accent: '#3f51b5' # deep purple
    background: '#f5f5f5' # light gray
    text: 'white' # dark gray

extra_css:
  - css/custom.css


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

markdown_extensions:
  - attr_list
  - md_in_html

font:
  text: monospace
  code: monospace

features:
  - navigation.sections
  - navigation.top
  - navigation.footer
  - toc.integrate
  - content.code.copy
  - content.code.annotate

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - tables
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true